apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mi-namespace
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: example
